# Generated by Django 5.2.12 on 2026-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
    ]
